# Generated by Django 5.1.15 on 2025-12-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_mining_case', models.BooleanField(default=False)),
                ('expected_return', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'csgonet_case',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='CaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('probability', models.DecimalField(decimal_places=14, max_digits=15)),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='public.case')),
            ],
            options={
                'db_table': 'csgonet_case_item',
                'ordering': ['-probability'],
            },
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='public.case')),
            ],
            options={
                'db_table': 'csgonet_case_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['case', 'changed_at'], name='csgonet_cas_case_id_e2560e_idx'), models.Index(fields=['field_changed'], name='csgonet_cas_field_c_0ee591_idx')],
            },
        ),
    ]
