# Generated by Django 5.1.15 on 2025-12-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseitem',
            name='probability',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
