# Generated by Django 5.1.15 on 2026-01-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_caseitem_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='max_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Highest possible return multiplier (best item / case price)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], help_text='Categorized risk level: low, medium, high', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='volatility',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Coefficient of variation - higher = more volatile', max_digits=10, null=True),
        ),
    ]
